### ISSUE TITLE
Only supports autoincrement primary keys ? 

### ISSUE THREAD

**Issue by spinx** [trappar/AliceGeneratorBundle#3]
Hi,

I'm using this with SF 3.1 and PHP7. 

It appears that the generation output assumes primary IDs are always autoincrement. 

If I use @ORM\GeneratedValue(strategy="NONE"), the IDs are not pulled into the output, and then on import naturally this fails. 

Can you confirm this as intended ? Are there any plans to change this ?

**Comment by trappar** [comment]
This is the intended behavior, but it would actually be fairly easy to change to work as you want. Might be a while before I get the chance to work on it, so if you want to take a stab at it I'd suggest you look at the `DoctrineProvider`'s `isPropertyNoOp` method. It might be possible to check if the identifier is autoincremented using the Doctrine ClassMetadata.

Alternatively if you write your own Provider or extend the DoctrineProvider and use that instead you can have full control over this process without having to change anything in this repo.

**Comment by spinx** [comment]
Cool, I just went digging and found isPropertyNoOp myself. I'll work on it, let's see what I come up with.
